/**
 * IBM i Fundamentals - Approved Lesson Sequence
 * Source: Spec 009 Section 5; D-CONT-001 resolved
 *
 * This file is the editable source of truth for lesson metadata.
 * Run `npm run seed` to sync this config into Supabase.
 *
 * Status values: 'Draft' | 'Review Ready' | 'Approved' | 'Published' | 'Unpublished / Archived'
 * All lessons start as 'Draft'. Change status here and re-run the seed script to publish.
 *
 * v2.0 fields (trackId, moduleId, difficulty, depth, tags, prerequisites,
 * relatedLessons, personaTags, aiTutorPrompts) are additive metadata from
 * Spec 009 v2.1 Section 11.3 / planning/CURRICULUM_EXPANSION_BLUEPRINT.md
 * Section 5. They do not change lessonOrder's existing role as the single
 * global ordering field the Learning Center, lesson navigation, and progress
 * "next lesson" calculation all currently depend on -- that behavior is
 * unchanged. See content/lessons/tracks.ts for the canonical track ID list.
 */

export type LessonDifficulty = 'beginner' | 'intermediate' | 'advanced'
export type LessonDepth = 'foundation' | 'professional'
export type PersonaTag = 'beginner' | 'working-developer' | 'support-developer' | 'interview-prep'

export interface LessonMetadata {
  slug: string
  title: string
  shortDescription: string
  lessonOrder: number
  learningPathId: string
  status: 'Draft' | 'Review Ready' | 'Approved' | 'Published' | 'Unpublished / Archived'
  contentSourcePath: string
  estimatedReadingTime?: number
  aiTutorStarterQuestion?: string
  /** v2.0 (optional): see content/lessons/tracks.ts for approved track IDs. */
  trackId?: string
  /** v2.0 (optional): free-text module identifier within trackId. */
  moduleId?: string
  /** v2.0 (optional): single declared difficulty value, no ranges. */
  difficulty?: LessonDifficulty
  /** v2.0 (optional): foundation = first explanation; professional = production-grade counterpart. */
  depth?: LessonDepth
  /** v2.0 (optional): free-form topical tags for future cross-track discovery. */
  tags?: string[]
  /** v2.0 (optional): lesson slugs that should be completed first. */
  prerequisites?: string[]
  /** v2.0 (optional): cross-track "see also" lesson slugs. */
  relatedLessons?: string[]
  /** v2.0 (optional): approved values only -- see PersonaTag. */
  personaTags?: PersonaTag[]
  /** v2.0 (optional): expands aiTutorStarterQuestion into 2-3 suggested prompts. */
  aiTutorPrompts?: string[]
}

export const IBM_I_FUNDAMENTALS_LESSONS: LessonMetadata[] = [
  {
    slug: 'what-is-ibm-i',
    title: 'What is IBM i?',
    shortDescription: 'A beginner-friendly introduction to IBM i, the integrated platform that runs on IBM Power Systems.',
    lessonOrder: 1,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/what-is-ibm-i.md',
    estimatedReadingTime: 5,
    aiTutorStarterQuestion: "What's the difference between IBM i and IBM Power Systems?",
    trackId: 'ibm-i-foundations',
    moduleId: 'what-ibm-i-is',
    difficulty: 'beginner',
    depth: 'foundation',
    personaTags: ['beginner'],
    aiTutorPrompts: ["What's the difference between IBM i and IBM Power Systems?"],
  },
  {
    slug: 'why-ibm-i-still-matters',
    title: 'Why IBM i Still Matters',
    shortDescription: 'Why organizations continue to rely on IBM i for critical systems, and what makes replacing it a slow, deliberate decision.',
    lessonOrder: 2,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/why-ibm-i-still-matters.md',
    estimatedReadingTime: 5,
    aiTutorStarterQuestion: "Why don't companies just migrate off IBM i if it's an older platform?",
    trackId: 'ibm-i-foundations',
    moduleId: 'why-ibm-i-still-matters',
    difficulty: 'beginner',
    depth: 'foundation',
    personaTags: ['beginner'],
    aiTutorPrompts: ["Why don't companies just migrate off IBM i if it's an older platform?"],
  },
  {
    slug: 'ibm-i-platform-overview',
    title: 'IBM i Platform Overview',
    shortDescription: 'A high-level map of the major parts of the IBM i platform and how they work together.',
    lessonOrder: 3,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/ibm-i-platform-overview.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'How do libraries, objects, and Db2 for i files all fit together on IBM i?',
    trackId: 'ibm-i-foundations',
    moduleId: 'the-big-picture-map',
    difficulty: 'beginner',
    depth: 'foundation',
    personaTags: ['beginner'],
    aiTutorPrompts: ['How do libraries, objects, and Db2 for i files all fit together on IBM i?'],
  },
  {
    slug: 'libraries-and-objects',
    title: 'Libraries and Objects',
    shortDescription: 'How IBM i organizes programs, files, and other objects using libraries, and why the library list matters.',
    lessonOrder: 4,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/libraries-and-objects.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: "What's the difference between an IBM i library and a folder on my computer?",
    trackId: 'libraries-objects-and-ifs',
    moduleId: 'objects-and-libraries',
    difficulty: 'beginner',
    depth: 'foundation',
    personaTags: ['beginner'],
    aiTutorPrompts: ["What's the difference between an IBM i library and a folder on my computer?"],
  },
  {
    slug: '5250-screen-basics',
    title: '5250 Screen Basics',
    shortDescription: 'What a 5250 screen is, how people navigate it, and why many IBM i applications still use it.',
    lessonOrder: 5,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/5250-screen-basics.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What do function keys like F3 typically do on a 5250 screen?',
    trackId: '5250-terminal-and-commands',
    moduleId: '5250-basics',
    difficulty: 'beginner',
    depth: 'foundation',
    personaTags: ['beginner'],
    aiTutorPrompts: ['What do function keys like F3 typically do on a 5250 screen?'],
  },
  {
    slug: 'physical-files-and-logical-files',
    title: 'Physical Files and Logical Files',
    shortDescription: 'How IBM i stores data in physical files and provides different views of that data through logical files.',
    lessonOrder: 6,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/physical-files-and-logical-files.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: "What's the difference between a physical file and a logical file on IBM i?",
    trackId: 'db2-for-i-and-dds',
    moduleId: 'physical-and-logical-files',
    difficulty: 'beginner',
    depth: 'foundation',
    personaTags: ['beginner'],
    aiTutorPrompts: ["What's the difference between a physical file and a logical file on IBM i?"],
  },
  {
    slug: 'introduction-to-rpgle',
    title: 'Introduction to RPGLE',
    shortDescription: "What RPGLE is, how it's used to build IBM i business applications, and how it connects to what you've learned so far.",
    lessonOrder: 7,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/introduction-to-rpgle.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What is the difference between fixed-format and free-format RPGLE?',
    trackId: 'rpgle-beginner',
    moduleId: 'what-rpgle-is',
    difficulty: 'beginner',
    depth: 'foundation',
    personaTags: ['beginner'],
    aiTutorPrompts: ['What is the difference between fixed-format and free-format RPGLE?'],
  },
  {
    slug: 'introduction-to-clle',
    title: 'Introduction to CLLE',
    shortDescription: "What CLLE is, how it's used to control and coordinate IBM i processes, and how it differs from RPGLE.",
    lessonOrder: 8,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/introduction-to-clle.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: "What's the difference between CLLE and RPGLE?",
    trackId: 'clle',
    moduleId: 'what-clle-is',
    difficulty: 'beginner',
    depth: 'foundation',
    personaTags: ['beginner'],
    aiTutorPrompts: ["What's the difference between CLLE and RPGLE?"],
  },
  {
    slug: 'introduction-to-db2-for-i',
    title: 'Introduction to Db2 for i',
    shortDescription: 'What Db2 for i is, how it relates to physical and logical files, and how applications access the data it stores.',
    lessonOrder: 9,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/introduction-to-db2-for-i.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'How does Db2 for i relate to physical and logical files?',
    trackId: 'db2-for-i-and-dds',
    moduleId: 'db2-for-i',
    difficulty: 'beginner',
    depth: 'foundation',
    personaTags: ['beginner'],
    aiTutorPrompts: ['How does Db2 for i relate to physical and logical files?'],
  },
  {
    slug: 'job-logs-and-spool-files-basics',
    title: 'Job Logs and Spool Files Basics',
    shortDescription: 'What job logs and spool files are, how they help with troubleshooting, and how they differ from physical and logical files.',
    lessonOrder: 10,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/job-logs-and-spool-files-basics.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: "What's the difference between a job log and a spool file?",
    trackId: 'debugging-and-job-logs',
    moduleId: 'job-logs-and-spool-files-basics',
    difficulty: 'beginner',
    depth: 'foundation',
    personaTags: ['beginner', 'support-developer'],
    aiTutorPrompts: ["What's the difference between a job log and a spool file?"],
  },
  {
    slug: 'basic-ibm-i-development-workflow',
    title: 'Basic IBM i Development Workflow',
    shortDescription: 'A general mental model for how IBM i developers move from source code to a tested, released program.',
    lessonOrder: 11,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/basic-ibm-i-development-workflow.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: "What's the difference between compiling a program and deploying it?",
    trackId: 'ibm-i-operations',
    moduleId: 'basic-development-workflow',
    difficulty: 'beginner',
    depth: 'foundation',
    personaTags: ['beginner', 'working-developer'],
    aiTutorPrompts: ["What's the difference between compiling a program and deploying it?"],
  },
  {
    slug: 'where-to-go-next',
    title: 'Where to Go Next',
    shortDescription: "A closing look at what you've learned across the IBM i Fundamentals path, and practical directions for continuing to learn.",
    lessonOrder: 12,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/where-to-go-next.md',
    estimatedReadingTime: 5,
    aiTutorStarterQuestion: 'What should I focus on learning next after finishing IBM i Fundamentals?',
    trackId: 'ibm-i-foundations',
    moduleId: 'where-to-go-next',
    difficulty: 'beginner',
    depth: 'foundation',
    personaTags: ['beginner'],
    aiTutorPrompts: ['What should I focus on learning next after finishing IBM i Fundamentals?'],
  },
  // --- Phase 1 Content Batch 1 (PR #58) ---
  // Published in PR #61 (Phase 1 Review + Publish Pass 1) after a technical
  // and structural review found no unresolved issues.
  {
    slug: 'as400-iseries-and-ibm-i-naming-explained',
    title: 'AS/400, iSeries, and IBM i Naming Explained',
    shortDescription: 'Why the same platform has been called AS/400, iSeries, System i, and IBM i, and how these names relate to each other.',
    lessonOrder: 13,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/as400-iseries-and-ibm-i-naming-explained.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: "If AS/400 and IBM i are the same platform, why do people still call it AS/400?",
    trackId: 'ibm-i-foundations',
    moduleId: 'what-ibm-i-is',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['naming', 'history', 'as400', 'iseries'],
    prerequisites: ['what-is-ibm-i'],
    relatedLessons: ['why-ibm-i-still-matters'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      "If AS/400 and IBM i are the same platform, why do people still call it AS/400?",
      'What is Power Systems, and how does it relate to IBM i?',
    ],
  },
  {
    slug: 'ibm-i-access-client-solutions-overview',
    title: 'IBM i Access Client Solutions Overview',
    shortDescription: 'What IBM i Access Client Solutions (ACS) is, what its main tools do, and how it fits alongside the 5250 interface.',
    lessonOrder: 14,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/ibm-i-access-client-solutions-overview.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What is the difference between the 5250 emulator in ACS and the database tool in ACS?',
    trackId: '5250-terminal-and-commands',
    moduleId: '5250-basics',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['acs', 'tools', '5250'],
    prerequisites: ['5250-screen-basics'],
    relatedLessons: ['5250-screen-basics'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What is the difference between the 5250 emulator in ACS and the database tool in ACS?',
      'Do I need special permission from IBM to install ACS?',
    ],
  },
  {
    slug: 'signing-on-user-profiles-and-current-library',
    title: 'Signing On, User Profiles, and Current Library',
    shortDescription: 'What happens when you sign on to IBM i, what a user profile is, and why your current library affects what you can find.',
    lessonOrder: 15,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/signing-on-user-profiles-and-current-library.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'How is current library related to the library list I learned about earlier?',
    trackId: '5250-terminal-and-commands',
    moduleId: 'system-values-and-signing-on',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['sign-on', 'user-profile', 'current-library'],
    prerequisites: ['5250-screen-basics'],
    relatedLessons: ['libraries-and-objects'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'How is current library related to the library list I learned about earlier?',
      'What kinds of things can a user profile restrict besides libraries?',
    ],
  },
  {
    slug: 'ibm-i-command-structure',
    title: 'Understanding IBM i Command Structure',
    shortDescription: 'How IBM i command names follow a verb-plus-object pattern, and how commands and parameters fit together.',
    lessonOrder: 16,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/ibm-i-command-structure.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What are some other common verb abbreviations used in IBM i commands besides CRT, DSP, WRK, and DLT?',
    trackId: '5250-terminal-and-commands',
    moduleId: 'navigating-menus-and-command-entry',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['commands', 'cl', 'syntax'],
    prerequisites: ['5250-screen-basics'],
    relatedLessons: ['using-f4-prompt-and-command-help'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What are some other common verb abbreviations used in IBM i commands besides CRT, DSP, WRK, and DLT?',
      "How do I know which parameters a command like CRTLIB actually needs?",
    ],
  },
  {
    slug: 'using-f4-prompt-and-command-help',
    title: 'Using F4 Prompt and Command Help',
    shortDescription: 'How to use the F4 prompt to fill in command parameters interactively, and how to use built-in command help.',
    lessonOrder: 17,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/using-f4-prompt-and-command-help.md',
    estimatedReadingTime: 5,
    aiTutorStarterQuestion: 'What happens if I press Enter on a prompt screen without filling in a required parameter?',
    trackId: '5250-terminal-and-commands',
    moduleId: 'command-parameters-and-prompting',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['f4', 'prompting', 'commands', 'help'],
    prerequisites: ['ibm-i-command-structure'],
    relatedLessons: ['ibm-i-command-structure'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What happens if I press Enter on a prompt screen without filling in a required parameter?',
      'Can I use F4 prompting on any IBM i command, or only some of them?',
    ],
  },
  {
    slug: 'common-ibm-i-object-types',
    title: 'Common IBM i Object Types',
    shortDescription: 'Common IBM i object types like *LIB, *FILE, *PGM, *USRPRF, and *OUTQ, and what each one is generally used for.',
    lessonOrder: 18,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/common-ibm-i-object-types.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What are some other IBM i object types besides *LIB, *FILE, *PGM, *USRPRF, and *OUTQ?',
    trackId: 'libraries-objects-and-ifs',
    moduleId: 'common-object-types',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['objects', 'object-types', 'libraries'],
    prerequisites: ['libraries-and-objects'],
    relatedLessons: ['ibm-i-platform-overview', 'libraries-and-objects'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What are some other IBM i object types besides *LIB, *FILE, *PGM, *USRPRF, and *OUTQ?',
      'How can I find out the object type of something I am looking at on IBM i?',
    ],
  },
  // --- Phase 1 Content Batch 2 (PR #59): libraries, objects, source members, IFS ---
  // Published in PR #61 (Phase 1 Review + Publish Pass 1) after a technical
  // and structural review found no unresolved issues.
  {
    slug: 'library-list-explained-in-depth',
    title: 'Library List Explained in Depth',
    shortDescription: 'The parts that make up an IBM i library list, the order IBM i searches them in, and how to view your own library list.',
    lessonOrder: 19,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/library-list-explained-in-depth.md',
    estimatedReadingTime: 7,
    aiTutorStarterQuestion: 'What is the difference between the system portion and the user portion of a library list?',
    trackId: 'libraries-objects-and-ifs',
    moduleId: 'library-list-in-depth',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['library-list', 'current-library', 'search-order'],
    prerequisites: ['libraries-and-objects', 'signing-on-user-profiles-and-current-library'],
    relatedLessons: ['signing-on-user-profiles-and-current-library'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What is the difference between the system portion and the user portion of a library list?',
      'How can I add a library to my library list temporarily using ADDLIBLE?',
    ],
  },
  {
    slug: 'source-physical-files-and-source-members',
    title: 'Source Physical Files and Source Members',
    shortDescription: 'What a source physical file is, what a source member is, and how RPGLE and CLLE source code is typically organized.',
    lessonOrder: 20,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/source-physical-files-and-source-members.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'How is a source member different from the compiled program it produces?',
    trackId: 'libraries-objects-and-ifs',
    moduleId: 'source-members',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['source-physical-file', 'source-member', 'rpgle', 'clle'],
    prerequisites: ['libraries-and-objects', 'physical-files-and-logical-files'],
    relatedLessons: ['common-ibm-i-object-types'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'How is a source member different from the compiled program it produces?',
      'What are some other common source physical file naming conventions besides QRPGLESRC?',
    ],
  },
  {
    slug: 'ifs-basics-for-ibm-i-beginners',
    title: 'IFS Basics for IBM i Beginners',
    shortDescription: 'What the Integrated File System (IFS) is, how its directory structure differs from libraries and objects, and when it is used.',
    lessonOrder: 21,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/ifs-basics-for-ibm-i-beginners.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What are some common uses of the IFS on IBM i besides configuration files?',
    trackId: 'libraries-objects-and-ifs',
    moduleId: 'ifs-basics',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['ifs', 'stream-files', 'directories'],
    prerequisites: ['libraries-and-objects'],
    relatedLessons: ['source-physical-files-and-source-members'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What are some common uses of the IFS on IBM i besides configuration files?',
      'How do I navigate to a specific IFS directory using ACS?',
    ],
  },
  {
    slug: 'native-objects-vs-stream-files',
    title: 'Native Objects vs Stream Files',
    shortDescription: 'The key differences between a native IBM i object and an IFS stream file, and how to recognize which model applies.',
    lessonOrder: 22,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/native-objects-vs-stream-files.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What commands are commonly used to copy data between a native object and a stream file?',
    trackId: 'libraries-objects-and-ifs',
    moduleId: 'native-objects-vs-stream-files',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['native-objects', 'ifs', 'stream-files', 'comparison'],
    prerequisites: ['common-ibm-i-object-types', 'ifs-basics-for-ibm-i-beginners'],
    relatedLessons: ['common-ibm-i-object-types', 'ifs-basics-for-ibm-i-beginners'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What commands are commonly used to copy data between a native object and a stream file?',
      'Why do some IBM i applications use stream files instead of native objects?',
    ],
  },
  {
    slug: 'object-naming-and-qualified-names-in-practice',
    title: 'Object Naming and Qualified Names in Practice',
    shortDescription: 'Basic IBM i object naming rules, what a qualified object name is, and why qualifying a library removes ambiguity.',
    lessonOrder: 23,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/object-naming-and-qualified-names-in-practice.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What happens if I use a qualified name for a library that does not exist?',
    trackId: 'libraries-objects-and-ifs',
    moduleId: 'object-naming-and-qualification',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['naming', 'qualified-names', 'objects'],
    prerequisites: ['common-ibm-i-object-types', 'libraries-and-objects'],
    relatedLessons: ['common-ibm-i-object-types', 'library-list-explained-in-depth'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What happens if I use a qualified name for a library that does not exist?',
      'Are there any exceptions to the traditional 10-character object naming limit?',
    ],
  },
  {
    slug: 'working-with-wrkobj-dspobjd-and-wrklib',
    title: 'Working with WRKOBJ, DSPOBJD, and WRKLIB',
    shortDescription: 'What the WRKOBJ, DSPOBJD, and WRKLIB commands are each used for, and which one to reach for depending on the task.',
    lessonOrder: 24,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/working-with-wrkobj-dspobjd-and-wrklib.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: "What kind of information does DSPOBJD show that WRKOBJ doesn't?",
    trackId: 'libraries-objects-and-ifs',
    moduleId: 'common-object-commands',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['wrkobj', 'dspobjd', 'wrklib', 'commands'],
    prerequisites: ['ibm-i-command-structure', 'using-f4-prompt-and-command-help', 'common-ibm-i-object-types'],
    relatedLessons: ['common-ibm-i-object-types', 'using-f4-prompt-and-command-help'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      "What kind of information does DSPOBJD show that WRKOBJ doesn't?",
      'How can I use WRKOBJ to search for an object across every library I have access to?',
    ],
  },
  // --- Phase 1 Content Batch 3 (PR #60): Db2 for i, DDS, keys, access paths, basic SQL ---
  // Published in PR #61 (Phase 1 Review + Publish Pass 1) after a technical
  // and structural review found no unresolved issues.
  {
    slug: 'dds-and-sql-two-ways-to-define-db2-for-i-data',
    title: 'DDS and SQL: Two Ways to Define Db2 for i Data',
    shortDescription: 'How Db2 for i data can be defined using either traditional DDS or modern SQL, and why both approaches still coexist today.',
    lessonOrder: 25,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/dds-and-sql-two-ways-to-define-db2-for-i-data.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'Why would a team choose SQL over DDS for a brand new IBM i project?',
    trackId: 'db2-for-i-and-dds',
    moduleId: 'dds-vs-sql-orientation',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['db2-for-i', 'dds', 'sql', 'orientation'],
    prerequisites: ['introduction-to-db2-for-i'],
    relatedLessons: ['introduction-to-db2-for-i', 'physical-files-and-logical-files'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'Why would a team choose SQL over DDS for a brand new IBM i project?',
      'Can an RPGLE program read data from a table that was created using SQL instead of DDS?',
    ],
  },
  {
    slug: 'physical-files-explained-in-depth',
    title: 'Physical Files Explained in Depth',
    shortDescription: 'The structure of a DDS-defined physical file, including record formats, in more detail than the introductory lesson.',
    lessonOrder: 26,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/physical-files-explained-in-depth.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What command is used to compile DDS source into a physical file object?',
    trackId: 'db2-for-i-and-dds',
    moduleId: 'physical-files-in-depth',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['physical-file', 'dds', 'record-format'],
    prerequisites: ['physical-files-and-logical-files', 'dds-and-sql-two-ways-to-define-db2-for-i-data'],
    relatedLessons: ['dds-and-sql-two-ways-to-define-db2-for-i-data'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What command is used to compile DDS source into a physical file object?',
      "Why can't a physical file have more than one record format?",
    ],
  },
  {
    slug: 'dds-field-definitions',
    title: 'DDS Field Definitions',
    shortDescription: 'How to read a simple DDS field definition: field name, data type, and length.',
    lessonOrder: 27,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/dds-field-definitions.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What is the difference between packed decimal and zoned decimal data in DDS?',
    trackId: 'db2-for-i-and-dds',
    moduleId: 'dds-field-definitions',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['dds', 'field-definitions', 'syntax'],
    prerequisites: ['physical-files-explained-in-depth', 'object-naming-and-qualified-names-in-practice'],
    relatedLessons: ['physical-files-explained-in-depth'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What is the difference between packed decimal and zoned decimal data in DDS?',
      'What are some other common DDS keywords besides name, type, and length?',
    ],
  },
  {
    slug: 'keyed-physical-files',
    title: 'Keyed Physical Files',
    shortDescription: 'What makes a physical file keyed, how key fields relate to DDS field definitions, and why keyed access matters.',
    lessonOrder: 28,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/keyed-physical-files.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What happens if I try to add a record with a duplicate key value to a keyed physical file?',
    trackId: 'db2-for-i-and-dds',
    moduleId: 'keyed-physical-files',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['keys', 'keyed-physical-file', 'dds'],
    prerequisites: ['physical-files-explained-in-depth', 'dds-field-definitions'],
    relatedLessons: ['dds-field-definitions'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What happens if I try to add a record with a duplicate key value to a keyed physical file?',
      'How is a keyed physical file different from a keyed logical file?',
    ],
  },
  {
    slug: 'logical-files-explained-in-depth',
    title: 'Logical Files Explained in Depth',
    shortDescription: 'What logical files can do beyond reordering data: keyed ordering, field selection, and select/omit.',
    lessonOrder: 29,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/logical-files-explained-in-depth.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: "How does a logical file's key relate to the key of its underlying physical file?",
    trackId: 'db2-for-i-and-dds',
    moduleId: 'logical-files-in-depth',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['logical-file', 'dds', 'views'],
    prerequisites: ['physical-files-and-logical-files', 'keyed-physical-files'],
    relatedLessons: ['keyed-physical-files'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      "How does a logical file's key relate to the key of its underlying physical file?",
      'What is a join logical file, at a high level?',
    ],
  },
  {
    slug: 'access-paths-and-why-they-matter',
    title: 'Access Paths and Why They Matter',
    shortDescription: 'What an access path is, how it supports keyed physical and logical files, and why it is a meaningful design tradeoff.',
    lessonOrder: 30,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/access-paths-and-why-they-matter.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'Does an arrival sequence physical file have any kind of access path at all?',
    trackId: 'db2-for-i-and-dds',
    moduleId: 'access-paths',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['access-path', 'indexing', 'keys'],
    prerequisites: ['keyed-physical-files', 'logical-files-explained-in-depth'],
    relatedLessons: ['keyed-physical-files', 'logical-files-explained-in-depth'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'Does an arrival sequence physical file have any kind of access path at all?',
      'Why might having too many logical files over one physical file become a concern?',
    ],
  },
  {
    slug: 'sql-tables-vs-dds-physical-files',
    title: 'SQL Tables vs DDS Physical Files',
    shortDescription: 'Comparing an SQL-defined table directly against a DDS-defined physical file: key similarities and practical differences.',
    lessonOrder: 31,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/sql-tables-vs-dds-physical-files.md',
    estimatedReadingTime: 7,
    aiTutorStarterQuestion: 'What is the SQL equivalent of a DDS key field?',
    trackId: 'db2-for-i-and-dds',
    moduleId: 'sql-tables-vs-dds',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['sql', 'dds', 'tables', 'comparison'],
    prerequisites: ['dds-and-sql-two-ways-to-define-db2-for-i-data', 'access-paths-and-why-they-matter'],
    relatedLessons: ['dds-and-sql-two-ways-to-define-db2-for-i-data'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What is the SQL equivalent of a DDS key field?',
      'Can I query a DDS-defined physical file using the same SQL syntax I would use for an SQL-defined table?',
    ],
  },
  {
    slug: 'basic-select-on-ibm-i',
    title: 'Basic SELECT on IBM i',
    shortDescription: 'What a basic SQL SELECT statement does, how to read one, and a common way to run one against Db2 for i data.',
    lessonOrder: 32,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/basic-select-on-ibm-i.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'How do I select specific columns instead of using * in a SELECT statement?',
    trackId: 'sql-for-ibm-i',
    moduleId: 'basic-select',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['sql', 'select', 'query-basics'],
    prerequisites: ['sql-tables-vs-dds-physical-files'],
    relatedLessons: ['sql-tables-vs-dds-physical-files', 'ibm-i-access-client-solutions-overview'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'How do I select specific columns instead of using * in a SELECT statement?',
      'What is the difference between the WHERE clause and just looking at every row myself?',
    ],
  },
  // --- RPGLE Foundations Batch 1 (PR #62): program structure through loops ---
  // Published in PR #64 (RPGLE Foundations Review + Publish Pass) after a
  // technical and structural review found no unresolved issues.
  {
    slug: 'rpgle-program-structure',
    title: 'RPGLE Program Structure',
    shortDescription: 'The main parts of a simple free-format RPGLE program: control options, declarations, calculations, and program end.',
    lessonOrder: 33,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/rpgle-program-structure.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What happens if I forget to set *INLR = *ON at the end of my program?',
    trackId: 'rpgle-beginner',
    moduleId: 'program-structure',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['rpgle', 'program-structure', 'free-format'],
    prerequisites: ['introduction-to-rpgle'],
    relatedLessons: ['introduction-to-rpgle'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What happens if I forget to set *INLR = *ON at the end of my program?',
      'What are some common ctl-opt settings besides DFTACTGRP?',
    ],
  },
  {
    slug: 'rpgle-source-layout-and-free-format-basics',
    title: 'RPGLE Source Layout and Free Format Basics',
    shortDescription: 'The basic layout rules of free-format RPGLE source: the **free marker, semicolons, comments, and indentation.',
    lessonOrder: 34,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/rpgle-source-layout-and-free-format-basics.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What kinds of errors happen if I forget a semicolon in free-format RPGLE?',
    trackId: 'rpgle-beginner',
    moduleId: 'source-layout-and-free-format',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['rpgle', 'free-format', 'syntax'],
    prerequisites: ['rpgle-program-structure'],
    relatedLessons: ['source-physical-files-and-source-members'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What kinds of errors happen if I forget a semicolon in free-format RPGLE?',
      'Why did IBM introduce free-format RPGLE if fixed-format already existed?',
    ],
  },
  {
    slug: 'variables-and-data-types-in-rpgle',
    title: 'Variables and Data Types in RPGLE',
    shortDescription: 'How to declare a simple RPGLE variable using dcl-s, and common RPGLE data types like char, packed, int, and ind.',
    lessonOrder: 35,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/variables-and-data-types-in-rpgle.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What is the difference between packed and int data types in RPGLE?',
    trackId: 'rpgle-beginner',
    moduleId: 'variables-and-data-types',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['rpgle', 'variables', 'data-types', 'dcl-s'],
    prerequisites: ['rpgle-source-layout-and-free-format-basics', 'dds-field-definitions'],
    relatedLessons: ['dds-field-definitions'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What is the difference between packed and int data types in RPGLE?',
      'What happens if I try to assign text to a packed decimal variable?',
    ],
  },
  {
    slug: 'constants-and-literals-in-rpgle',
    title: 'Constants and Literals in RPGLE',
    shortDescription: 'What a literal value is, what an RPGLE constant (dcl-c) is, and why named constants are often better than repeated literals.',
    lessonOrder: 36,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/constants-and-literals-in-rpgle.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What happens if I try to change the value of a dcl-c constant while the program is running?',
    trackId: 'rpgle-beginner',
    moduleId: 'constants-and-literals',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['rpgle', 'constants', 'literals', 'dcl-c'],
    prerequisites: ['variables-and-data-types-in-rpgle'],
    relatedLessons: ['variables-and-data-types-in-rpgle'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What happens if I try to change the value of a dcl-c constant while the program is running?',
      'What are some good examples of values that make sense as named constants?',
    ],
  },
  {
    slug: 'expressions-and-assignment-in-rpgle',
    title: 'Expressions and Assignment in RPGLE',
    shortDescription: 'How to read and write RPGLE assignment statements, and common arithmetic and comparison operators used in expressions.',
    lessonOrder: 37,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/expressions-and-assignment-in-rpgle.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What happens if I divide by zero in an RPGLE expression?',
    trackId: 'rpgle-beginner',
    moduleId: 'expressions-and-assignment',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['rpgle', 'expressions', 'assignment', 'operators'],
    prerequisites: ['variables-and-data-types-in-rpgle', 'constants-and-literals-in-rpgle'],
    relatedLessons: ['variables-and-data-types-in-rpgle'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What happens if I divide by zero in an RPGLE expression?',
      'How does RPGLE decide the order to calculate an expression with more than one operator?',
    ],
  },
  {
    slug: 'if-else-in-rpgle',
    title: 'IF / ELSE in RPGLE',
    shortDescription: 'How to read and write if / elseif / else blocks in free-format RPGLE using comparison operators.',
    lessonOrder: 38,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/if-else-in-rpgle.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'Can I nest one if block inside another in RPGLE?',
    trackId: 'rpgle-beginner',
    moduleId: 'conditional-logic-if-else',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['rpgle', 'conditionals', 'if-else'],
    prerequisites: ['expressions-and-assignment-in-rpgle'],
    relatedLessons: ['select-when-other-in-rpgle'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'Can I nest one if block inside another in RPGLE?',
      'What is the difference between using multiple elseif branches and using SELECT / WHEN?',
    ],
  },
  {
    slug: 'select-when-other-in-rpgle',
    title: 'SELECT / WHEN / OTHER in RPGLE',
    shortDescription: 'How to read and write select / when / other blocks in free-format RPGLE, and when they beat a long elseif chain.',
    lessonOrder: 39,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/select-when-other-in-rpgle.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'When should I use select instead of if / elseif?',
    trackId: 'rpgle-beginner',
    moduleId: 'conditional-logic-select',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['rpgle', 'conditionals', 'select-when'],
    prerequisites: ['if-else-in-rpgle'],
    relatedLessons: ['if-else-in-rpgle'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'When should I use select instead of if / elseif?',
      'Can a when condition in RPGLE check more than one value at once?',
    ],
  },
  {
    slug: 'do-loops-and-basic-iteration-in-rpgle',
    title: 'DO Loops and Basic Iteration in RPGLE',
    shortDescription: 'How to read and write for, dow, and dou loops in free-format RPGLE, and when each one is a natural fit.',
    lessonOrder: 40,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/do-loops-and-basic-iteration-in-rpgle.md',
    estimatedReadingTime: 7,
    aiTutorStarterQuestion: 'What happens if I write a dow loop whose condition never becomes false?',
    trackId: 'rpgle-beginner',
    moduleId: 'loops-and-iteration',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['rpgle', 'loops', 'iteration', 'dow', 'dou', 'for'],
    prerequisites: ['if-else-in-rpgle', 'expressions-and-assignment-in-rpgle'],
    relatedLessons: ['if-else-in-rpgle'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What happens if I write a dow loop whose condition never becomes false?',
      'Can I use for to count backwards instead of counting up?',
    ],
  },
  // --- RPGLE Foundations Batch 2 (PR #63): BIFs through debugging ---
  // Published in PR #64 (RPGLE Foundations Review + Publish Pass) after a
  // technical and structural review found no unresolved issues.
  {
    slug: 'built-in-functions-in-rpgle',
    title: 'Built-in Functions in RPGLE',
    shortDescription: 'What RPGLE built-in functions (BIFs) are, and how to use %TRIM, %LEN, %SUBST, %CHAR, and %DEC.',
    lessonOrder: 41,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/built-in-functions-in-rpgle.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What are some other commonly used RPGLE built-in functions besides %TRIM, %LEN, %SUBST, %CHAR, and %DEC?',
    trackId: 'rpgle-beginner',
    moduleId: 'built-in-functions',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['rpgle', 'built-in-functions', 'bifs'],
    prerequisites: ['expressions-and-assignment-in-rpgle'],
    relatedLessons: ['variables-and-data-types-in-rpgle'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What are some other commonly used RPGLE built-in functions besides %TRIM, %LEN, %SUBST, %CHAR, and %DEC?',
      'What happens if %SUBST tries to pull out more characters than the value actually has?',
    ],
  },
  {
    slug: 'data-structures-in-rpgle',
    title: 'Data Structures in RPGLE',
    shortDescription: 'How to declare an RPGLE data structure with dcl-ds, group related subfields, and why qualified is good practice.',
    lessonOrder: 42,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/data-structures-in-rpgle.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: "What happens if I don't use qualified and two data structures have a subfield with the same name?",
    trackId: 'rpgle-beginner',
    moduleId: 'data-structures',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['rpgle', 'data-structures', 'dcl-ds'],
    prerequisites: ['variables-and-data-types-in-rpgle'],
    relatedLessons: ['variables-and-data-types-in-rpgle', 'dds-field-definitions'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      "What happens if I don't use qualified and two data structures have a subfield with the same name?",
      'Can a data structure be used as a parameter passed to a procedure?',
    ],
  },
  {
    slug: 'arrays-in-rpgle',
    title: 'Arrays in RPGLE',
    shortDescription: 'How to declare an RPGLE array with dim, access elements by index, and loop through an array.',
    lessonOrder: 43,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/arrays-in-rpgle.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What happens if I try to access an array index beyond its declared size?',
    trackId: 'rpgle-beginner',
    moduleId: 'arrays',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['rpgle', 'arrays', 'dim'],
    prerequisites: ['variables-and-data-types-in-rpgle', 'do-loops-and-basic-iteration-in-rpgle'],
    relatedLessons: ['do-loops-and-basic-iteration-in-rpgle'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What happens if I try to access an array index beyond its declared size?',
      'Can I use %LEN or %TRIM on an individual array element the same way I would on a regular variable?',
    ],
  },
  {
    slug: 'indicators-in-modern-rpgle',
    title: 'Indicators in Modern RPGLE',
    shortDescription: 'Why numbered indicators (*IN01-*IN99) were historically common, and why modern RPGLE favors named indicator variables.',
    lessonOrder: 44,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/indicators-in-modern-rpgle.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'Why were numbered indicators so commonly used in older RPG display file programs specifically?',
    trackId: 'rpgle-beginner',
    moduleId: 'indicators',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['rpgle', 'indicators', 'legacy'],
    prerequisites: ['if-else-in-rpgle', 'variables-and-data-types-in-rpgle'],
    relatedLessons: ['if-else-in-rpgle'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'Why were numbered indicators so commonly used in older RPG display file programs specifically?',
      'Is *INLR the only special built-in indicator besides numbered ones?',
    ],
  },
  {
    slug: 'procedures-and-subprocedures-in-rpgle',
    title: 'Procedures and Subprocedures in RPGLE',
    shortDescription: 'Why RPGLE programs are broken into subprocedures, and how to write and call a simple one with dcl-proc.',
    lessonOrder: 45,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/procedures-and-subprocedures-in-rpgle.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'Can a subprocedure call another subprocedure?',
    trackId: 'rpgle-beginner',
    moduleId: 'procedures-and-subprocedures',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['rpgle', 'procedures', 'subprocedures', 'dcl-proc'],
    prerequisites: ['rpgle-program-structure', 'if-else-in-rpgle'],
    relatedLessons: ['parameters-and-prototypes-in-rpgle'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'Can a subprocedure call another subprocedure?',
      "What's the difference between a subprocedure and the older subroutine style from fixed-format RPG?",
    ],
  },
  {
    slug: 'parameters-and-prototypes-in-rpgle',
    title: 'Parameters and Prototypes in RPGLE',
    shortDescription: 'How to write a subprocedure that accepts parameters and returns a value using dcl-pi, and what a prototype is for.',
    lessonOrder: 46,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/parameters-and-prototypes-in-rpgle.md',
    estimatedReadingTime: 7,
    aiTutorStarterQuestion: "What happens if I try to change a const parameter's value inside a subprocedure?",
    trackId: 'rpgle-beginner',
    moduleId: 'parameters-and-prototypes',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['rpgle', 'parameters', 'prototypes', 'dcl-pi'],
    prerequisites: ['procedures-and-subprocedures-in-rpgle'],
    relatedLessons: ['procedures-and-subprocedures-in-rpgle'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      "What happens if I try to change a const parameter's value inside a subprocedure?",
      'Why does dcl-pi use *n instead of just retyping the subprocedure name?',
    ],
  },
  {
    slug: 'basic-error-handling-in-rpgle',
    title: 'Basic Error Handling in RPGLE',
    shortDescription: 'Why error handling matters in RPGLE, and how to use monitor / on-error / endmon to catch a runtime error.',
    lessonOrder: 47,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/basic-error-handling-in-rpgle.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What kinds of RPGLE operations commonly need a monitor block around them?',
    trackId: 'rpgle-beginner',
    moduleId: 'basic-error-handling',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['rpgle', 'error-handling', 'monitor'],
    prerequisites: ['if-else-in-rpgle', 'built-in-functions-in-rpgle'],
    relatedLessons: ['if-else-in-rpgle'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What kinds of RPGLE operations commonly need a monitor block around them?',
      'What happens if an error occurs outside of any monitor block in my program?',
    ],
  },
  {
    slug: 'debugging-rpgle-programs',
    title: 'Debugging RPGLE Programs',
    shortDescription: 'Beginner-friendly ways to investigate an RPGLE program: dsply tracing, the ILE source debugger, and job logs.',
    lessonOrder: 48,
    learningPathId: 'ibm-i-fundamentals',
    status: 'Published',
    contentSourcePath: 'content/lessons/debugging-rpgle-programs.md',
    estimatedReadingTime: 6,
    aiTutorStarterQuestion: 'What is the difference between using dsply for debugging and using the ILE source debugger?',
    trackId: 'rpgle-beginner',
    moduleId: 'debugging-basics',
    difficulty: 'beginner',
    depth: 'foundation',
    tags: ['rpgle', 'debugging', 'strdbg', 'job-logs'],
    prerequisites: ['rpgle-program-structure'],
    relatedLessons: ['basic-error-handling-in-rpgle', 'job-logs-and-spool-files-basics'],
    personaTags: ['beginner'],
    aiTutorPrompts: [
      'What is the difference between using dsply for debugging and using the ILE source debugger?',
      'What command starts the ILE source debugger on IBM i?',
    ],
  },
]
