/**
 * 5250 Command Practice -- planned exercise list (PR #135 skeleton).
 *
 * Sourced from planning/5250_PRACTICE_LAB_SQL_CONSOLE_DESIGN_PROPOSAL.md
 * Section 4 (PR #134). Every exercise is `status: 'planned'` in this PR --
 * no command dispatch/simulation engine exists yet (see lib/practice-lab/
 * types.ts header). That is PR #136's scope.
 */
import type { PracticeLabExercise } from '@/lib/practice-lab/types'

export const PRACTICE_LAB_5250_EXERCISES: PracticeLabExercise[] = [
  {
    id: '5250-01',
    slug: 'command-line-basics',
    title: 'Command line and prompt style basics',
    labType: '5250',
    difficulty: 'beginner',
    summary: 'Get comfortable with the 5250 command-line pattern: type a command, optionally press F4 to prompt for parameters, then press Enter.',
    learningObjectives: ['Recognize the type-then-Enter command line pattern', 'Understand what F4 prompting does'],
    relatedLessonSlugs: ['using-f4-prompt-and-command-help'],
    status: 'planned',
  },
  {
    id: '5250-02',
    slug: 'wrklib',
    title: 'Use WRKLIB',
    labType: '5250',
    difficulty: 'beginner',
    summary: 'List libraries and understand what a library is in IBM i object terms.',
    learningObjectives: ['Run WRKLIB', 'Explain what a library is'],
    relatedLessonSlugs: ['working-with-wrkobj-dspobjd-and-wrklib', 'library-list-explained-in-depth'],
    status: 'planned',
  },
  {
    id: '5250-03',
    slug: 'wrkobj',
    title: 'Use WRKOBJ',
    labType: '5250',
    difficulty: 'beginner',
    summary: 'List objects within a library and recognize object type codes like *PGM and *FILE.',
    learningObjectives: ['Run WRKOBJ against a library', 'Identify common object type codes'],
    relatedLessonSlugs: ['working-with-wrkobj-dspobjd-and-wrklib'],
    status: 'planned',
  },
  {
    id: '5250-04',
    slug: 'dspobjd',
    title: 'Use DSPOBJD',
    labType: '5250',
    difficulty: 'beginner',
    summary: "Display a single object's description/metadata, and see how that differs from a WRKOBJ worklist.",
    learningObjectives: ['Run DSPOBJD against a single object', 'Explain DSPOBJD vs WRKOBJ'],
    relatedLessonSlugs: ['working-with-wrkobj-dspobjd-and-wrklib'],
    status: 'planned',
  },
  {
    id: '5250-05',
    slug: 'wrksplf',
    title: 'Use WRKSPLF',
    labType: '5250',
    difficulty: 'beginner',
    summary: 'List spool files and understand how a spool file relates to the job that created it.',
    learningObjectives: ['Run WRKSPLF', 'Explain what a spool file is'],
    relatedLessonSlugs: ['working-with-spool-files-using-wrksplf'],
    status: 'planned',
  },
  {
    id: '5250-06',
    slug: 'wrkoutq',
    title: 'Use WRKOUTQ',
    labType: '5250',
    difficulty: 'beginner',
    summary: 'Understand output queues as the holding area spool files live in before printing.',
    learningObjectives: ['Run WRKOUTQ', 'Explain the difference between an output queue and a spool file'],
    relatedLessonSlugs: ['working-with-output-queues-using-wrkoutq', 'working-with-spool-files-using-wrksplf'],
    status: 'planned',
  },
  {
    id: '5250-07',
    slug: 'dspjob',
    title: 'Use DSPJOB',
    labType: '5250',
    difficulty: 'intermediate',
    summary: "Inspect a job's details -- status, job log, open files -- as a troubleshooting starting point.",
    learningObjectives: ['Run DSPJOB', 'Explain what a job log is used for'],
    relatedLessonSlugs: ['dspjob-and-job-information-basics'],
    status: 'planned',
  },
  {
    id: '5250-08',
    slug: 'wrkactjob',
    title: 'Use WRKACTJOB',
    labType: '5250',
    difficulty: 'intermediate',
    summary: "Recognize the system-wide \"what's currently running\" view and its status columns.",
    learningObjectives: ['Run WRKACTJOB', 'Recognize common job status values'],
    relatedLessonSlugs: ['wrkactjob-basics-for-developers', 'job-status-values-explained'],
    status: 'planned',
  },
  {
    id: '5250-09',
    slug: 'investigate-msgw-job',
    title: 'Investigate a MSGW job',
    labType: '5250',
    difficulty: 'intermediate',
    summary: 'Recognize MSGW (message-wait) status and the workflow to find out what message a job is waiting on.',
    learningObjectives: ['Identify a job in MSGW status', 'Explain that MSGW means waiting, not hung or crashed'],
    relatedLessonSlugs: ['job-status-values-explained', 'reading-ibm-i-message-ids'],
    status: 'planned',
  },
  {
    id: '5250-10',
    slug: 'wrkobjlck-object-lock',
    title: 'Find an object lock using WRKOBJLCK',
    labType: '5250',
    difficulty: 'intermediate',
    summary: 'Recognize that "why can\'t I update/delete this object" is often an object-lock question, and WRKOBJLCK is the tool to answer it.',
    learningObjectives: ['Run WRKOBJLCK against an object', 'Explain the difference between a shared and an exclusive lock'],
    relatedLessonSlugs: ['object-locks-basics', 'handling-object-locks-as-a-developer'],
    status: 'planned',
  },
]
